version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_db
    # volumes:
    #   - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  # redis:
  #   build: ./redis
  #   container_name: redis
  #   # command: redis-server /redis.conf
  #   # environment:
  #   #   REDIS_PASSWORD: 
  #   #   REDIS_TLS_ENABLED: "yes"
  #   #   REDIS_TLS_CERT_FILE: /usr/local/etc/redis/redis.crt
  #   #   REDIS_TLS_KEY_FILE: /usr/local/etc/redis/redis.key
  #   #   REDIS_TLS_CA_FILE: /usr/local/etc/redis/ca.crt
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./data/redis:/data

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 1234
  #   ports:
  #     - 27017:27017

  # busybox:
  #   image: busybox
  #   container_name: busybox
  #   command: tail -F anyFile

  # curl:
  #   image: curlimages/curl:8.00.1
  #   container_name: curl
  #   command: tail -F anyFile